[package]
name = "phishing_email"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
chrono = "0.4.39"
dotenv = "0.15.0"
mysql = "26.0.0"
serde = { version = "1.0.219", features = ["derive"] }
